//javascript

console.log("HOLA CAMILO")

//Este comando imprime el mensaje "HOLA CAMILO" en la consola estándar. console.log() se utiliza para imprimir mensajes de registro normales.

//javascript

console.warn("HOLA CAMILO")

//Este comando imprime el mensaje "HOLA CAMILO" en la consola de advertencias. console.warn() se utiliza para imprimir advertencias en la consola.

//avascript

console.error("HOLA CAMILO")

//Este comando imprime el mensaje "HOLA CAMILO" en la consola de errores. console.error() se utiliza para imprimir mensajes de error en la consola.

//avascript

console.error(new Error("Error encontrado"))

//Este comando imprime un objeto Error con el mensaje "Error encontrado" en la consola de errores. console.error() se utiliza para imprimir mensajes de error en la consola. En este caso, se crea un nuevo objeto Error con el mensaje específico y se pasa como argumento a console.error(). Esto es útil para capturar y mostrar errores específicos dentro de tu aplicación.